export const Api = {
  // @ts-ignore
  BASE_URL_WITHOUT_LAST_SLASH: config.domain,
  ADMIN: '/admin',
  AFISHA_EVENTS: '/afisha-events',
  API: '/api',
  ARTICLE: '/article',
  ARTICLES: '/articles',
  BANNER: '/banner',
  DISLIKE: '/dislike',
  CITYFACES: '/cityfaces',
  COMMENT: '/comment',
  COMMENTS: '/comments',
  FAQ: '/faq',
  FAQ_EXPERT: '/faq-expert',
  FAQ_ITEM: '/faq-item',
  FAQ_ITEMS: '/faq-items',
  FAQ_TOPIC: '/faq-topic',
  LIKES: '/likes',
  LIKE: '/create',
  LIKE_DELETE: '/delete',
  MENU: '/menu',
  MENU_LIST: '/menu-list',
  NEXT_ARTICLE: '/next-endless-news',
  OFFERS: '/offers',
  PDF: '/pdf',
  QUIZZES: '/quizzes',
  QUIZ: '/quiz',
  REDIRECTS: '/redirects',
  SEO: '/seos',
  SETTINGS: '/settings',
  SETTINGS_DOMAINS_WHITE: '/white-links',
  STATIC_PAGES: '/static-pages',
  TAG: '/tag',
  USERS: '/users',
  VOTINGS: '/votings',
};

